databases:
  - name: wholesale-db
    databaseName: wholesale_db
    user: wholesale_user
    plan: free

services:
  - type: web
    name: pocket-santhai
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: bash start.sh
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: DATABASE_ENGINE
        value: django.db.backends.postgresql
      - key: DATABASE_NAME
        fromDatabase:
          name: wholesale-db
          property: database
      - key: DATABASE_USER
        fromDatabase:
          name: wholesale-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: wholesale-db
          property: password
      - key: DATABASE_HOST
        fromDatabase:
          name: wholesale-db
          property: host
      - key: DATABASE_PORT
        fromDatabase:
          name: wholesale-db
          property: port
      - key: REDIS_URL
        fromService:
          type: redis
          name: pocket-santhai-redis
          property: connectionString

  - type: redis
    name: pocket-santhai-redis
    region: singapore
    plan: free
    ipAllowList: [] # only allow internal connections
