# Generated by Django 5.2.14 on 2026-09-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_alter_customuser_email_alter_stockitem_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='category',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
